Repository Start9Labs/start-os, pull requests merged in 2021-09, with the labels that each got.

#511 fixes revisions for notifications
  appmgr/src/notifications.rs
Labels: bug, embassyd

#503 implement package.action rpc/cli command
  appmgr/src/action/mod.rs
  appmgr/src/lib.rs
Labels: embassyd, P1 - This Release

#508 implements module level logging
  appmgr/Cargo.lock
  appmgr/Cargo.toml
  appmgr/src/bin/embassyd.rs
  appmgr/src/context/rpc.rs
  appmgr/src/util/logger.rs
Labels: enhancement, embassyd, P1 - This Release
