Repository Start9Labs/start-os, pull requests merged in 2021-12, with the labels that each got.

#887 adds flag to manager shared state describing whether health checks sh…
  appmgr/src/config/mod.rs
  appmgr/src/error.rs
  appmgr/src/manager/health.rs
  appmgr/src/manager/mod.rs
  appmgr/src/status/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release

#878 Bugfix/disable uasp
  appmgr/embassy-init.service
  appmgr/src/disk/mod.rs
  appmgr/src/disk/quirks.rs
  appmgr/src/disk/util.rs
  build/fstab
  build/initialization.sh
  build/write-image.sh
Labels: embassyd, P1 - Blocks Release

#911 closes #910
  ui/src/app/components/form-object/form-object.component.ts
Labels: Bug, UI, P0 - Blocks Dev

#913 setup complete
  setup-wizard/README.md
  setup-wizard/src/app/pages/embassy/embassy.page.ts
  setup-wizard/src/app/pages/init/init.page.ts
  setup-wizard/src/app/services/api/api.service.ts
  setup-wizard/src/app/services/api/live-api.service.ts
  setup-wizard/src/app/services/api/mock-api.service.ts
  setup-wizard/src/app/services/state.service.ts
Labels: Enhancement, UI, P0 - Blocks Dev

#916 skip prompt if no dep issues
  ui/src/app/components/install-wizard/dependents/dependents.component.html
  ui/src/app/components/install-wizard/dependents/dependents.component.ts
  ui/src/app/components/install-wizard/prebaked-wizards.ts
Labels: UI

#921 Feature/setup attach
  appmgr/src/disk/main.rs
  appmgr/src/init.rs
  appmgr/src/setup.rs
Labels: embassyd, P1 - Blocks Release

#928 reduce health check locking
  appmgr/src/dependencies.rs
  appmgr/src/manager/health.rs
  appmgr/src/status/health_check.rs
  appmgr/src/status/mod.rs
Labels: embassyd, P1 - Blocks Release

#934 disable login as `ubuntu`
  build/initialization.sh
  build/write-image.sh
Labels: P1 - Blocks Release, Builds, SECURITY

#931 delete container before action
  appmgr/src/action/docker.rs
Labels: Bug, embassyd, P1 - Blocks Release

#936 enable gzip compression
  appmgr/src/nginx/diagnostic-ui.conf
  appmgr/src/nginx/main-ui.conf.template
  appmgr/src/nginx/setup-wizard.conf
Labels: Enhancement, embassyd, P2 - Desirable, Performance

#932 correctly handle self as current dependent
  appmgr/src/config/mod.rs
  appmgr/src/dependencies.rs
  appmgr/src/install/cleanup.rs
  appmgr/src/install/mod.rs
  appmgr/src/install/update.rs
Labels: Bug, embassyd, P1 - Blocks Release

#933 allow mdns cifs shares
  appmgr/src/backup/target/cifs.rs
  appmgr/src/disk/mount/filesystem/cifs.rs
  appmgr/src/net/mdns.rs
  build/initialization.sh
  setup-wizard/src/app/modals/cifs-modal/cifs-modal.page.html
  setup-wizard/src/app/modals/cifs-modal/cifs-modal.page.ts
  setup-wizard/src/app/pages/recover/recover.page.html
  ui/src/app/components/backup-drives/backup-drives.component.html
  ui/src/app/components/backup-drives/backup-drives.component.ts
  ui/src/app/components/install-wizard/prebaked-wizards.ts
  ui/src/app/components/status/status.component.html
  ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.html
  ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.html
  ui/src/app/pages/server-routes/ssh-keys/ssh-keys.page.ts
  ui/src/app/util/package-loading-progress.ts
  ui/src/global.scss
Labels: Enhancement, embassyd, P1 - Blocks Release

#968 add set-marketplace rpc
  appmgr/src/bin/embassyd.rs
  appmgr/src/context/rpc.rs
  appmgr/src/lib.rs
  appmgr/src/marketplace.rs
  appmgr/src/nginx/main-ui.conf.template
Labels: Enhancement, embassyd, P1 - Blocks Release

#970 rename symbols about dependencies
  appmgr/src/config/mod.rs
  appmgr/src/dependencies.rs
  appmgr/src/install/cleanup.rs
  appmgr/src/install/mod.rs
Labels: embassyd, P2 - Desirable, Refactor

#974 change sounds away from mario, replace their use sites
  appmgr/src/bin/embassy-init.rs
  appmgr/src/bin/embassyd.rs
  appmgr/src/shutdown.rs
  appmgr/src/sound.rs
  appmgr/src/update/mod.rs
Labels: Enhancement, embassyd, P1 - Blocks Release

#975 upgrade all packages before baking image
  build/initialization.sh
Labels: Enhancement, P1 - Blocks Release, Builds

#989 fix setup recovery
  setup-wizard/src/app/modals/cifs-modal/cifs-modal.page.ts
  setup-wizard/src/app/pages/recover/recover.page.ts
  setup-wizard/src/app/services/api/api.service.ts
Labels: Bug, UI

#987 fix get_hostname
  appmgr/src/hostname.rs
Labels: Bug, embassyd, P1 - Blocks Release

#985 retry failed pause
  appmgr/src/manager/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release

#998 color the logs
  diagnostic-ui/package-lock.json
  diagnostic-ui/package.json
  diagnostic-ui/src/app/pages/logs/logs.page.ts
Labels: Enhancement, UI, P1 - Blocks Release

#961 refactor(app-show): refactor component
  ui/.prettierrc
  ui/angular.json
  ui/package-lock.json
  ui/package.json
  ui/src/app/app.module.ts
  ui/src/app/pages/apps-routes/app-list/app-list-pkg/app-list-pkg.component.html
  ui/src/app/pages/apps-routes/app-list/app-list-pkg/app-list-pkg.component.ts
  ui/src/app/pages/apps-routes/app-show/app-show.module.ts
  ui/src/app/pages/apps-routes/app-show/app-show.page.html
  ui/src/app/pages/apps-routes/app-show/app-show.page.scss
  ui/src/app/pages/apps-routes/app-show/app-show.page.ts
  ui/src/app/pages/apps-routes/app-show/components/app-show-dependencies/app-show-dependencies.component.html
  ui/src/app/pages/apps-routes/app-show/components/app-show-dependencies/app-show-dependencies.component.scss
  ui/src/app/pages/apps-routes/app-show/components/app-show-dependencies/app-show-dependencies.component.ts
  ui/src/app/pages/apps-routes/app-show/components/app-show-header/app-show-header.component.html
  ui/src/app/pages/apps-routes/app-show/components/app-show-header/app-show-header.component.scss
  ui/src/app/pages/apps-routes/app-show/components/app-show-header/app-show-header.component.ts
  ui/src/app/pages/apps-routes/app-show/components/app-show-health-checks/app-show-health-checks.component.html
  ui/src/app/pages/apps-routes/app-show/components/app-show-health-checks/app-show-health-checks.component.scss
  ui/src/app/pages/apps-routes/app-show/components/app-show-health-checks/app-show-health-checks.component.ts
  ui/src/app/pages/apps-routes/app-show/components/app-show-menu/app-show-menu.component.html
  ui/src/app/pages/apps-routes/app-show/components/app-show-menu/app-show-menu.component.ts
  ui/src/app/pages/apps-routes/app-show/components/app-show-progress/app-show-progress.component.html
  ui/src/app/pages/apps-routes/app-show/components/app-show-progress/app-show-progress.component.scss
  ui/src/app/pages/apps-routes/app-show/components/app-show-progress/app-show-progress.component.ts
  ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.html
  ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.scss
  ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.ts
  ui/src/app/pages/apps-routes/app-show/pipes/health-color.pipe.ts
  ui/src/app/pages/apps-routes/app-show/pipes/to-buttons.pipe.ts
  ui/src/app/pages/apps-routes/app-show/pipes/to-dependencies.pipe.ts
  ui/src/app/pages/apps-routes/app-show/pipes/to-health-checks.pipe.ts
  ui/src/app/pages/apps-routes/app-show/pipes/to-status.pipe.ts
  ui/src/app/pipes/install-state.pipe.ts
  ui/src/app/services/api/api.service.factory.ts
  ui/src/app/services/modal.service.ts
  ui/src/app/services/patch-db/data-model.ts
  ui/src/app/services/pkg-status-rendering.service.ts
  ui/src/app/services/ui-launcher.service.ts
  ui/src/app/util/get-package-info.ts
  ui/src/app/util/package-loading-progress.ts
  ui/tslint.json
Labels: UI, Refactor, Needs Triage

#1008 Bugfix/metrics leak
  ui/src/app/pages/apps-routes/app-metrics/app-metrics.page.html
  ui/src/app/pages/apps-routes/app-metrics/app-metrics.page.ts
  ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list.page.html
  ui/src/app/pages/server-routes/server-metrics/server-metrics.page.html
  ui/src/app/pages/server-routes/server-metrics/server-metrics.page.scss
  ui/src/app/pages/server-routes/server-metrics/server-metrics.page.ts
  ui/src/app/pages/server-routes/wifi/wifi.page.ts
  ui/src/global.scss
Labels: Bug, UI, P2 - Desirable

#1011 adds package renaming for vaultwarden, abstracted in case we have oth…
  appmgr/src/setup.rs
Labels: Enhancement, embassyd, P1 - Blocks Release
