Repository Start9Labs/start-os, pull requests merged in 2021-11, with the labels that each got.

#738 Build README update
  build/README.md
Labels: Docs, Builds

#764 Feature/eos disk filtering
  appmgr/Cargo.lock
  appmgr/Cargo.toml
  appmgr/src/disk/util.rs
Labels: Enhancement, embassyd, P1 - Blocks Release

#765 refactor: remove sync daemon
  appmgr/Cargo.lock
  appmgr/Cargo.toml
  appmgr/src/backup/backup_bulk.rs
  appmgr/src/bin/embassyd.rs
  appmgr/src/config/mod.rs
  appmgr/src/context/rpc.rs
  appmgr/src/context/setup.rs
  appmgr/src/control.rs
  appmgr/src/manager/mod.rs
  appmgr/src/manager/sync.rs
  appmgr/src/status/mod.rs
Labels: embassyd, P1 - Blocks Release, Refactor

#776 fixes leaf certs to use leaf cert extensions
  appmgr/src/net/ssl.rs
Labels: Bug, embassyd, P1 - Blocks Release

#784 Feature/always gen certs
  appmgr/src/backup/backup_bulk.rs
  appmgr/src/net/mod.rs
  appmgr/src/net/nginx.rs
  appmgr/src/net/ssl.rs
  appmgr/src/volume.rs
  system-images/compat/Cargo.lock
Labels: Bug, embassyd, P1 - Blocks Release

#786 Feature/rate limiting
  appmgr/src/middleware/auth.rs
Labels: Enhancement, embassyd, P1 - Blocks Release

#794 implement cert download endpoint
  appmgr/src/net/ssl.rs
  appmgr/src/static_server.rs
Labels: Enhancement, embassyd, P1 - Blocks Release

#808 Feature/s9pk sideload
  appmgr/src/bin/embassyd.rs
  appmgr/src/context/cli.rs
  appmgr/src/context/rpc.rs
  appmgr/src/core/mod.rs
  appmgr/src/core/rpc_continuations.rs
  appmgr/src/install/mod.rs
  appmgr/src/lib.rs
  appmgr/src/nginx/main-ui.conf.template
Labels: Enhancement, embassyd, P1 - Blocks Release

#806 just set this.metrics
  ui/src/app/pages/server-routes/server-metrics/server-metrics.page.ts
Labels: UI, Needs Triage

#813 install messaging
  ui/src/app/components/status/status.component.html
Labels: UI, Needs Triage

#816 clean up transient state on boot
  appmgr/src/context/rpc.rs
  appmgr/src/db/model.rs
  appmgr/src/error.rs
  appmgr/src/install/cleanup.rs
  appmgr/src/install/mod.rs
  appmgr/src/manager/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release

#831 Bugfix/wifi race conditions
  appmgr/src/context/rpc.rs
  appmgr/src/net/wifi.rs
Labels: Bug, embassyd, P1 - Blocks Release

#841 recovery drive failing
  setup-wizard/src/app/pages/recover/recover.page.html
  setup-wizard/src/app/services/api/live-api.service.ts
Labels: Bug, UI, P1 - Blocks Release

#843 logs monospace no new line in between
  ui/src/app/components/logs/logs.page.html
  ui/src/app/components/logs/logs.page.ts
Labels: Enhancement, UI, P2 - Desirable

#844 empty list issue
  ui/src/app/pages/apps-routes/app-list/app-list.page.ts
Labels: Bug, UI, Needs Triage

#846 Bugfix/protocol consistency
  appmgr/src/install/mod.rs
  appmgr/src/update/mod.rs
  ui/src/app/components/install-wizard/prebaked-wizards.ts
  ui/src/app/pages/apps-routes/app-list/app-list.page.ts
  ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.ts
  ui/src/app/services/api/api.types.ts
Labels: Bug, UI, embassyd, P0 - Blocks Dev

#852 Feature/starting status
  appmgr/src/backup/backup_bulk.rs
  appmgr/src/control.rs
  appmgr/src/manager/mod.rs
  appmgr/src/manager/sync.rs
  appmgr/src/status/mod.rs
Labels: Enhancement, embassyd, P1 - Blocks Release

#855 adds name, description; changes critical boolean to severity enum
  appmgr/src/status/health_check.rs
  appmgr/src/status/mod.rs
Labels: Enhancement, embassyd, P1 - Blocks Release

#857 adds defaults to healthcheck severity
  appmgr/src/status/health_check.rs
Labels: Enhancement, embassyd, P1 - Blocks Release

#864 union tag description
  ui/src/app/components/form-object/form-object.component.html
  ui/src/app/components/form-object/form-object.component.ts
  ui/src/app/services/api/api.fixures.ts
Labels: Bug, UI, P1 - Blocks Release

#870 fixes issue where packages that were already broken would not report …
  appmgr/src/dependencies.rs
Labels: Bug, embassyd, P1 - Blocks Release

#873 blacklist uas kernel module
  build/write-image.sh
Labels: P1 - Blocks Release, Builds
