Repository Start9Labs/start-os, pull requests merged in 2022-06, with the labels that each got.

#1466 Link to tor address on LAN setup page (#1277)
  frontend/projects/ui/src/app/pages/server-routes/lan/lan.page.html
  frontend/projects/ui/src/app/pages/server-routes/lan/lan.page.ts
Labels: Enhancement, UI, P2 - Desirable

#1467 Update contribution and frontend readme
  CONTRIBUTING.md
  frontend/README.md
  frontend/package.json
Labels: Docs, UI, P2 - Desirable

#1486 UI cosmetic improvements
  frontend/projects/shared/styles/shared.scss
  frontend/projects/ui/src/app/app/global/services/update-toast.service.ts
  frontend/projects/ui/src/app/app/snek/snek.directive.ts
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.ts
  frontend/projects/ui/src/app/components/logs/logs.page.ts
  frontend/projects/ui/src/app/modals/app-config/app-config.page.ts
  frontend/projects/ui/src/app/modals/app-recover-select/app-recover-select.page.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-actions/app-actions.page.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.ts
  frontend/projects/ui/src/app/pages/developer-routes/developer-list/developer-list.page.ts
  frontend/projects/ui/src/app/pages/developer-routes/developer-menu/developer-menu.page.ts
  frontend/projects/ui/src/app/pages/login/login.page.ts
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list-content/marketplace-list-content.component.html
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.html
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-status/marketplace-status.component.html
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-status/marketplace-status.component.ts
  frontend/projects/ui/src/app/pages/notifications/notifications.page.ts
  frontend/projects/ui/src/app/pages/server-routes/marketplaces/marketplaces.page.ts
  frontend/projects/ui/src/app/pages/server-routes/preferences/preferences.page.ts
  frontend/projects/ui/src/app/pages/server-routes/restore/restore.component.ts
  frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.page.ts
  frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
  frontend/projects/ui/src/app/pages/server-routes/sessions/sessions.page.ts
  frontend/projects/ui/src/app/pages/server-routes/ssh-keys/ssh-keys.page.ts
  frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.page.ts
  frontend/projects/ui/src/app/services/api/api.fixures.ts
  frontend/projects/ui/src/app/services/api/mock-patch.ts
  frontend/projects/ui/src/app/services/marketplace.service.ts
  frontend/projects/ui/src/app/services/server-config.service.ts
  frontend/projects/ui/src/styles.scss
Labels: Bug, Enhancement, UI, P2 - Desirable

#1500 generate unique ca names based off of server id
  backend/src/net/ssl.rs
Labels: Enhancement, embassyd, P2 - Desirable

#1501 allow embassy-cli not as root
  backend/Cargo.lock
  backend/Cargo.toml
  backend/install-sdk.sh
  backend/src/backup/target/mod.rs
  backend/src/context/cli.rs
  backend/src/context/diagnostic.rs
  backend/src/context/rpc.rs
  backend/src/context/sdk.rs
  backend/src/context/setup.rs
  backend/src/developer/mod.rs
  backend/src/disk/mount/filesystem/block_dev.rs
  backend/src/disk/mount/filesystem/cifs.rs
  backend/src/disk/mount/filesystem/ecryptfs.rs
  backend/src/disk/mount/filesystem/label.rs
  backend/src/disk/mount/filesystem/mod.rs
  backend/src/error.rs
  backend/src/lib.rs
  backend/src/s9pk/builder.rs
  backend/src/s9pk/reader.rs
  backend/src/setup.rs
  backend/src/util/config.rs
  backend/src/util/mod.rs
Labels: Bug, Enhancement, embassy-sdk

#1509 fixes serialization of regex pattern + description
  backend/src/config/spec.rs
Labels: Bug, embassyd, P0 - Blocks Dev

#1508 allow interactive TTY if available
  backend/build-dev.sh
  backend/build-portable-dev.sh
  backend/build-portable.sh
  backend/build-prod.sh
  system-images/compat/build.sh
Labels: Builds

#1513 Rework install progress types and pipes for clarity
  frontend/README.md
  frontend/projects/marketplace/src/pages/show/package/package.component.html
  frontend/projects/marketplace/src/pages/show/package/package.component.scss
  frontend/projects/ui/src/app/components/status/status.component.html
  frontend/projects/ui/src/app/components/status/status.component.module.ts
  frontend/projects/ui/src/app/components/status/status.component.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-pkg/app-list-pkg.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-reorder/app-list-reorder.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.module.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.page.html
  frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.page.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-progress/app-show-progress.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-progress/app-show-progress.component.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/pipes/progress-data.pipe.ts
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show-controls/marketplace-show-controls.component.html
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show-controls/marketplace-show-controls.component.ts
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show-controls/marketplace-show-controls.page.scss
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.html
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-status/marketplace-status.component.html
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-status/marketplace-status.component.ts
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-status/marketplace-status.module.ts
  frontend/projects/ui/src/app/pipes/install-progress/install-progress.module.ts
  frontend/projects/ui/src/app/pipes/install-progress/install-progress.pipe.ts
  frontend/projects/ui/src/app/pipes/launchable/launchable.pipe.ts
  frontend/projects/ui/src/app/services/api/api.fixures.ts
  frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
  frontend/projects/ui/src/app/services/api/mock-patch.ts
  frontend/projects/ui/src/app/services/config.service.ts
  frontend/projects/ui/src/app/services/patch-db/data-model.ts
  frontend/projects/ui/src/app/services/pkg-status-rendering.service.ts
  frontend/projects/ui/src/app/types/install-progress.ts
  frontend/projects/ui/src/app/types/package-state.ts
  frontend/projects/ui/src/app/util/package-loading-progress.ts
  frontend/proxy.conf-sample.json
  frontend/proxy.conf.json.sample
Labels: UI, Refactor

#1491 Feature/copy logs
  frontend/projects/setup-wizard/src/app/pages/success/success.page.ts
  frontend/projects/shared/styles/shared.scss
  frontend/projects/ui/src/app/modals/action-success/action-success.page.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-interfaces/app-interfaces.page.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-logs/app-logs.page.html
  frontend/projects/ui/src/app/pages/apps-routes/app-logs/app-logs.page.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-properties/app-properties.page.ts
  frontend/projects/ui/src/app/pages/server-routes/server-logs/server-logs.page.html
  frontend/projects/ui/src/app/pages/server-routes/server-logs/server-logs.page.ts
  frontend/projects/ui/src/app/pages/server-routes/server-specs/server-specs.page.ts
Labels: Enhancement, UI, P2 - Desirable

#1507 display QR code for interfaces
  frontend/projects/ui/src/app/app/preloader/preloader.component.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-interfaces/app-interfaces-item.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-interfaces/app-interfaces.page.ts
Labels: Enhancement, UI, P2 - Desirable

#1516 fix "missing proxy" error in embassy-cli
  backend/src/config/action.rs
  backend/src/context/cli.rs
  system-images/compat/Cargo.lock
Labels: Bug, P0 - Blocks Dev, embassy-cli

#1506 fixes a bug where nginx will crash if eos goes into diagnostic mode a…
  backend/src/nginx/diagnostic-ui.conf
Labels: Bug, Needs Triage

#1533 fixes #1169
  backend/src/net/tor.rs
Labels: Bug, embassyd, P2 - Desirable

#1536 add restart rpc and status
  backend/src/backup/backup_bulk.rs
  backend/src/control.rs
  backend/src/dependencies.rs
  backend/src/manager/sync.rs
  backend/src/status/mod.rs
Labels: Enhancement, embassyd, P2 - Desirable

#1482 add restart button to service show page and restart rpc api
  backend/src/backup/backup_bulk.rs
  backend/src/control.rs
  backend/src/dependencies.rs
  backend/src/manager/sync.rs
  backend/src/status/mod.rs
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.scss
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.ts
  frontend/projects/ui/src/app/services/api/api.types.ts
  frontend/projects/ui/src/app/services/api/embassy-api.service.ts
  frontend/projects/ui/src/app/services/api/embassy-live-api.service.ts
  frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
  frontend/projects/ui/src/app/services/patch-db/data-model.ts
  frontend/projects/ui/src/app/services/pkg-status-rendering.service.ts
Labels: Enhancement, UI, P2 - Desirable

#1547 fix incorrect error message for deserialization in ValueSpecString
  backend/src/config/spec.rs
  backend/test/config-spec/lnd-correct.yaml
Labels: Bug, embassyd

#1546 fix dependency/dependent id issue
  backend/src/config/mod.rs
Labels: Bug, embassyd

#1534 add textarea to ValueSpecString
  backend/src/config/spec.rs
Labels: Enhancement, embassyd, P2 - Desirable

#1549 fix backend builds for safe git config
  backend/build-prod.sh
  system-images/compat/build.sh
Labels: Bug, Builds

#1559 update should send version not version spec
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show-controls/marketplace-show-controls.component.ts
Labels: Bug

#1560 add reset password option
  .gitignore
  backend/sqlx-data.json
  backend/src/auth.rs
  backend/src/control.rs
  backend/src/middleware/auth.rs
  backend/src/setup.rs
  libs/js_engine/src/lib.rs
Labels: Enhancement, embassyd, P1 - Blocks Release, embassy-cli

#1490 Reset password through setup wizard
  .gitignore
  backend/sqlx-data.json
  backend/src/auth.rs
  backend/src/control.rs
  backend/src/middleware/auth.rs
  backend/src/setup.rs
  frontend/projects/setup-wizard/src/app/pages/recover/recover.page.ts
  frontend/projects/setup-wizard/src/app/services/api/api.service.ts
  frontend/projects/setup-wizard/src/app/services/api/live-api.service.ts
  frontend/projects/setup-wizard/src/app/services/api/mock-api.service.ts
  frontend/projects/setup-wizard/src/app/services/state.service.ts
  frontend/projects/ui/src/app/pages/login/login.page.ts
  frontend/projects/ui/src/app/services/http.service.ts
  libs/js_engine/src/lib.rs
Labels: Enhancement, UI, embassyd, P1 - Blocks Release

#1558 fix bugs with config and clean up dev options
  frontend/projects/marketplace/src/pipes/filter-packages.pipe.ts
  frontend/projects/shared/src/pipes/emver/emver.pipe.ts
  frontend/projects/ui/src/app/components/form-object/form-error.component.html
  frontend/projects/ui/src/app/components/form-object/form-label.component.html
  frontend/projects/ui/src/app/components/form-object/form-object.component.html
  frontend/projects/ui/src/app/components/form-object/form-object.component.scss
  frontend/projects/ui/src/app/components/form-object/form-object.component.ts
  frontend/projects/ui/src/app/components/logs/logs.page.html
  frontend/projects/ui/src/app/modals/app-config/app-config.page.ts
  frontend/projects/ui/src/app/modals/generic-form/generic-form.page.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.page.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.html
  frontend/projects/ui/src/app/pages/developer-routes/developer-menu/developer-menu.page.html
  frontend/projects/ui/src/app/pages/developer-routes/developer-menu/developer-menu.page.ts
  frontend/projects/ui/src/app/pages/developer-routes/developer-menu/form-info.ts
  frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
  frontend/projects/ui/src/app/pages/server-routes/sideload/sideload.page.html
  frontend/projects/ui/src/app/services/marketplace.service.ts
  frontend/projects/ui/src/app/services/pkg-status-rendering.service.ts
Labels: UI, P1 - Blocks Release

#1571 adjust service marketplace button for installation source relevance
  frontend/projects/shared/src/util/misc.util.ts
  frontend/projects/shared/styles/shared.scss
  frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.page.html
  frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.page.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/pipes/to-buttons.pipe.ts
  frontend/projects/ui/src/app/services/marketplace.service.ts
  frontend/projects/ui/src/app/util/web.util.ts
Labels: Enhancement, UI, P1 - Blocks Release

#1573 fix connection failure display monitoring and other style changes
  frontend/projects/marketplace/src/pages/list/categories/categories.component.html
  frontend/projects/marketplace/src/pages/list/categories/categories.component.ts
  frontend/projects/marketplace/src/pages/show/about/about.component.html
  frontend/projects/marketplace/src/pages/show/about/about.component.scss
  frontend/projects/marketplace/src/pipes/filter-packages.pipe.ts
  frontend/projects/setup-wizard/src/app/pages/recover/recover.page.html
  frontend/projects/ui/src/app/app/menu/menu.component.html
  frontend/projects/ui/src/app/app/preloader/preloader.component.ts
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.html
  frontend/projects/ui/src/app/components/status/status.component.html
  frontend/projects/ui/src/app/components/status/status.component.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-icon/app-list-icon.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-icon/app-list-icon.component.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-pkg/app-list-pkg.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-pkg/app-list-pkg.component.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-reorder/app-list-reorder.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-reorder/app-list-reorder.component.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.page.html
  frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.page.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-health-checks/app-show-health-checks.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-health-checks/app-show-health-checks.component.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-status/app-show-status.component.ts
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-list/marketplace-list-content/marketplace-list-content.component.html
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-status/marketplace-status.component.html
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-status/marketplace-status.component.scss
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-status/marketplace-status.component.ts
  frontend/projects/ui/src/app/pages/notifications/notifications.page.html
  frontend/projects/ui/src/app/pages/server-routes/marketplaces/marketplaces.page.html
  frontend/projects/ui/src/app/pages/server-routes/sessions/sessions.page.html
  frontend/projects/ui/src/app/pages/server-routes/sessions/sessions.page.ts
  frontend/projects/ui/src/app/pages/server-routes/ssh-keys/ssh-keys.page.html
  frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.page.html
  frontend/projects/ui/src/app/services/connection.service.ts
Labels: UI, P1 - Blocks Release

#1570 Fix/mask generic inputs
  Makefile
  frontend/assets/fonts/Redacted/redacted.regular.ttf
  frontend/projects/ui/src/app/components/form-object/form-object.component.html
  frontend/projects/ui/src/app/components/form-object/form-object.component.scss
  frontend/projects/ui/src/app/modals/generic-input/generic-input.component.html
  frontend/projects/ui/src/app/modals/generic-input/generic-input.component.module.ts
  frontend/projects/ui/src/app/modals/generic-input/generic-input.component.ts
  frontend/projects/ui/src/styles.scss
Labels: Enhancement, UI, P1 - Blocks Release

#1577 Fix/sideload icon type
  frontend/projects/marketplace/src/types/marketplace-manifest.ts
  frontend/projects/ui/src/app/pages/server-routes/sideload/sideload.page.html
  frontend/projects/ui/src/app/pages/server-routes/sideload/sideload.page.scss
  frontend/projects/ui/src/app/pages/server-routes/sideload/sideload.page.ts
  frontend/projects/ui/src/app/services/api/api.fixures.ts
  frontend/projects/ui/src/app/services/api/api.types.ts
  frontend/projects/ui/src/app/services/api/mock-patch.ts
  frontend/projects/ui/src/app/services/eos.service.ts
  frontend/projects/ui/src/app/services/patch-db/data-model.ts
Labels: Enhancement, UI, P2 - Desirable

#1576 selective backups and better drive selection interface
  backend/src/backup/backup_bulk.rs
  backend/src/db/model.rs
  backend/src/init.rs
  frontend/projects/ui/src/app/app/preloader/preloader.component.ts
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.html
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.scss
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.ts
  frontend/projects/ui/src/app/modals/backup-select/backup-select.module.ts
  frontend/projects/ui/src/app/modals/backup-select/backup-select.page.html
  frontend/projects/ui/src/app/modals/backup-select/backup-select.page.scss
  frontend/projects/ui/src/app/modals/backup-select/backup-select.page.ts
  frontend/projects/ui/src/app/pages/developer-routes/developer-list/developer-list.page.html
  frontend/projects/ui/src/app/pages/server-routes/marketplaces/marketplaces.page.ts
  frontend/projects/ui/src/app/pages/server-routes/server-backup/backing-up/backing-up.component.html
  frontend/projects/ui/src/app/pages/server-routes/server-backup/backing-up/backing-up.component.ts
  frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.module.ts
  frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.page.html
  frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.page.ts
  frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.html
  frontend/projects/ui/src/app/services/api/api.fixures.ts
  frontend/projects/ui/src/app/services/api/api.types.ts
  frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
  frontend/projects/ui/src/app/services/api/mock-patch.ts
  frontend/projects/ui/src/app/services/eos.service.ts
  frontend/projects/ui/src/app/services/patch-db/data-model.ts
Labels: Enhancement, UI, embassyd, P2 - Desirable

#1575 Feat/use modern tor
  build/initialization.sh
Labels: Enhancement, Needs Triage, Builds

#1582 fix backup lock ordering
  backend/src/backup/backup_bulk.rs
Labels: Bug

#1587 switch to utc
  build/initialization.sh
Labels: Bug, Builds

#1589 filter package ids when backing up
  backend/src/backup/backup_bulk.rs
Labels: Bug, embassyd
