Repository Start9Labs/start-os, pull requests merged in 2022-03, with the labels that each got.

#1312 fix back button
  frontend/projects/ui/src/app/pages/apps-routes/app-properties/app-properties.page.ts
Labels: Bug

#1325 handle new content-types from marketplace.get
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/marketplace.rs
Labels: embassyd

#1332 use consistent config file type
  backend/src/context/rpc.rs
  backend/src/context/setup.rs
Labels: Bug, embassyd, embassy-cli

#1334 include shared scss in setup-wizard and diagnostic-ui
  frontend/angular.json
Labels: Bug, P1 - Blocks Release

#1333 whitelist samsung T7
  backend/src/disk/quirks.rs
Labels: embassyd

#1340 allow websockets to containers
  backend/src/net/nginx.conf.template
  backend/src/nginx/main-ui.conf.template
Labels: embassyd, P1 - Blocks Release

#1349 fix init
  build/initialization.sh
Labels: Bug, Builds

#1351 Fix/config obj list
  Makefile
  frontend/projects/ui/src/app/components/form-object/form-object.component.html
  frontend/projects/ui/src/app/components/form-object/form-object.component.ts
  frontend/projects/ui/src/app/pages/server-routes/marketplaces/marketplaces.page.ts
  frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.page.ts
  frontend/projects/ui/src/app/pkg-config/config-types.ts
  frontend/projects/ui/src/app/services/api/api.fixures.ts
  frontend/projects/ui/src/app/services/api/mock-patch.ts
Labels: Bug, UI, P0 - Blocks Dev

#1350 run fsck on startup
  backend/src/bin/embassy-init.rs
  backend/src/diagnostic.rs
  backend/src/disk/fsck.rs
  backend/src/disk/main.rs
  backend/src/disk/mod.rs
  backend/src/setup.rs
Labels: Enhancement, embassyd, P1 - Blocks Release

#1355 update sqlx directly, and allow patch bumps from other packages
  backend/Cargo.lock
  backend/Cargo.toml
Labels: Bug, embassyd, P1 - Blocks Release

#1357 Fix marketplace button display
  frontend/projects/marketplace/src/pages/show/package/package.component.html
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace-show/marketplace-show.page.html
Labels: Bug, UI, P0 - Blocks Dev

#1358 Feature/diagnostic repair disk
  frontend/projects/diagnostic-ui/src/app/pages/home/home.page.html
  frontend/projects/diagnostic-ui/src/app/pages/home/home.page.ts
  frontend/projects/diagnostic-ui/src/app/services/api/api.service.ts
  frontend/projects/diagnostic-ui/src/app/services/api/live-api.service.ts
  frontend/projects/diagnostic-ui/src/app/services/api/mock-api.service.ts
  frontend/projects/ui/src/app/app.component.html
  frontend/projects/ui/src/app/app.component.ts
  frontend/projects/ui/src/app/components/backup-drives/backup.service.ts
  frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.html
  frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
  frontend/projects/ui/src/app/services/api/embassy-api.service.ts
  frontend/projects/ui/src/app/services/api/embassy-live-api.service.ts
  frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
  frontend/projects/ui/src/app/services/api/mock-patch.ts
  frontend/projects/ui/src/app/services/local-storage.service.ts
Labels: UI, P1 - Blocks Release

#1362 wait for time sync up to 60s
  backend/embassy-init.service
  backend/src/init.rs
  build/initialization.sh
Labels: Bug, embassyd

#1367 fix issue where boot label reverts on quirk change
  backend/src/update/mod.rs
  backend/src/version/v0_3_0_1.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1366 Fix/misc 0.3.0.1
  frontend/projects/diagnostic-ui/src/app/pages/home/home.page.ts
  frontend/projects/ui/src/app/components/form-object/form-object.component.html
  frontend/projects/ui/src/app/modals/generic-input/generic-input.component.html
  frontend/projects/ui/src/app/pages/apps-routes/app-show/components/app-show-health-checks/app-show-health-checks.component.html
Labels: UI

#1368 better eager loading and better error messaging for backup flow
  frontend/config-sample.json
  frontend/projects/marketplace/src/pages/show/about/about.component.html
  frontend/projects/marketplace/src/pages/show/additional/additional.component.html
  frontend/projects/shared/src/types/workspace-config.ts
  frontend/projects/ui/src/app/app.component.html
  frontend/projects/ui/src/app/components/backup-drives/backup.service.ts
  frontend/projects/ui/src/app/components/form-object/form-object.component.scss
  frontend/projects/ui/src/app/components/install-wizard/install-wizard.component.scss
  frontend/projects/ui/src/app/components/install-wizard/notes/notes.component.html
  frontend/projects/ui/src/app/components/install-wizard/notes/notes.component.ts
  frontend/projects/ui/src/app/components/install-wizard/prebaked-wizards.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-list/app-list-rec/app-list-rec.component.ts
  frontend/projects/ui/src/app/pages/server-routes/restore/restore.component.ts
  frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.page.ts
  frontend/projects/ui/src/app/services/api/api.fixures.ts
  frontend/projects/ui/src/app/services/api/api.types.ts
  frontend/projects/ui/src/app/services/api/embassy-live-api.service.ts
  frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
  frontend/projects/ui/src/app/services/api/mock-patch.ts
  frontend/projects/ui/src/app/services/config.service.ts
  frontend/projects/ui/src/app/services/eos.service.ts
  frontend/projects/ui/src/styles.scss
Labels: UI, P1 - Blocks Release
