Repository Start9Labs/start-os, pull requests merged in 2022-02, with the labels that each got.

#1158 Changes to ubuntu 21.10 at the base image
  Makefile
  build/initialization.sh
Labels: Enhancement, P0 - Blocks Dev, Builds

#1162 perform docker state build if folder doesn't exist
  backend/src/init.rs
  build/write-image.sh
Labels: Bug, embassyd, P1 - Blocks Release, Builds

#1175 fix: Properties
  frontend/projects/ui/src/app/util/properties.util.ts
Labels: Bug, P1 - Blocks Release

#1173 Trying code editor
  frontend/angular.json
  frontend/package-lock.json
  frontend/package.json
  frontend/projects/ui/src/app/app-routing.module.ts
  frontend/projects/ui/src/app/app.component.html
  frontend/projects/ui/src/app/app.component.ts
  frontend/projects/ui/src/app/app.module.ts
  frontend/projects/ui/src/app/modals/markdown/markdown.page.ts
  frontend/projects/ui/src/app/pages/developer-routes/dev-config/dev-config.module.ts
  frontend/projects/ui/src/app/pages/developer-routes/dev-config/dev-config.page.html
  frontend/projects/ui/src/app/pages/developer-routes/dev-config/dev-config.page.scss
  frontend/projects/ui/src/app/pages/developer-routes/dev-config/dev-config.page.ts
  frontend/projects/ui/src/app/pages/developer-routes/dev-instructions/dev-instructions.module.ts
  frontend/projects/ui/src/app/pages/developer-routes/dev-instructions/dev-instructions.page.html
  frontend/projects/ui/src/app/pages/developer-routes/dev-instructions/dev-instructions.page.scss
  frontend/projects/ui/src/app/pages/developer-routes/dev-instructions/dev-instructions.page.ts
  frontend/projects/ui/src/app/pages/developer-routes/developer-list/developer-list.module.ts
  frontend/projects/ui/src/app/pages/developer-routes/developer-list/developer-list.page.html
  frontend/projects/ui/src/app/pages/developer-routes/developer-list/developer-list.page.scss
  frontend/projects/ui/src/app/pages/developer-routes/developer-list/developer-list.page.ts
  frontend/projects/ui/src/app/pages/developer-routes/developer-routing.module.ts
  frontend/projects/ui/src/app/pages/server-routes/preferences/preferences.page.html
  frontend/projects/ui/src/app/pages/server-routes/preferences/preferences.page.ts
  frontend/projects/ui/src/app/pkg-config/config-types.ts
  frontend/projects/ui/src/app/services/api/embassy-mock-api.service.ts
  frontend/projects/ui/src/app/services/api/mock-patch.ts
  frontend/projects/ui/src/app/services/local-storage.service.ts
  frontend/projects/ui/src/app/services/patch-db/data-model.ts
  frontend/projects/ui/src/app/services/server-config.service.ts
Labels: Enhancement, UI, Needs Triage

#1181 bugfix: inverts mapping for lan config
  backend/src/net/interface.rs
  backend/src/net/nginx.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1192 fixes calculation of disk percentage
  backend/src/system.rs
Labels: Bug, embassyd, P3 - Eventual

#1191 removes charge tune
  backend/src/bin/embassyd.rs
  backend/src/sound.rs
Labels: embassyd, P2 - Desirable

#1196 implement delete-recovered
  backend/sqlx-data.json
  backend/src/context/rpc.rs
  backend/src/install/cleanup.rs
  backend/src/install/mod.rs
  backend/src/lib.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1165 fix lock scope
  backend/src/backup/backup_bulk.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1195 prevents packages from producing conflicting ssl configs
  backend/src/db/mod.rs
  backend/src/db/model.rs
  backend/src/error.rs
  backend/src/install/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1198 add time-wait-sync to embassy-init dependencies
  backend/embassy-init.service
Labels: Bug, embassyd, P1 - Blocks Release

#1204 Bugfix/ntp before embassy init
  backend/embassy-init.service
Labels: Bug, P0 - Blocks Dev, Builds

#1202 Bugfix/conflicting ssl configs
  backend/src/db/mod.rs
  backend/src/db/model.rs
  backend/src/db/package.rs
  backend/src/error.rs
  backend/src/install/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1206 use product key instead of id for drive verification
  backend/src/setup.rs
Labels: embassyd

#1210 add vim and jq
  build/initialization.sh
Labels: Enhancement, Builds

#1211 handle crash loops better
  backend/src/manager/mod.rs
Labels: Enhancement, embassyd

#1219 fix (de)serialization of min and max
  backend/src/install/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1218 fix overlay disabling when looking at disk drives
  build/initialization.sh
  build/write-image.sh
Labels: Bug, P1 - Blocks Release, Builds

#1224 Fixes/recover dying during starting
  backend/src/action/docker.rs
  backend/src/backup/restore.rs
  backend/src/context/rpc.rs
  backend/src/util/logger.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1221 retry file copies during migration
  backend/src/backup/backup_bulk.rs
  backend/src/backup/restore.rs
  backend/src/backup/target/cifs.rs
  backend/src/backup/target/mod.rs
  backend/src/disk/main.rs
  backend/src/disk/mount/backup.rs
  backend/src/disk/mount/filesystem/block_dev.rs
  backend/src/disk/mount/filesystem/cifs.rs
  backend/src/disk/mount/filesystem/ecryptfs.rs
  backend/src/disk/mount/filesystem/label.rs
  backend/src/disk/mount/filesystem/mod.rs
  backend/src/disk/mount/guard.rs
  backend/src/disk/util.rs
  backend/src/setup.rs
  backend/src/update/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1229 fix bug that prevents rpc context from dropping without server shutdown
  backend/src/bin/embassyd.rs
  backend/src/context/rpc.rs
  backend/src/setup.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1232 re-add logging now that it isn't part of rpc context
  backend/src/bin/embassyd.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1231 backup refresh messaging
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.html
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.ts
Labels: P1 - Blocks Release

#1235 show bottom border on input focus
  frontend/projects/ui/src/styles.scss
  frontend/styles/global.scss
Labels: P1 - Blocks Release

#1238 copy changes to cifs backups
  frontend/projects/setup-wizard/src/app/pages/recover/recover.page.html
  frontend/projects/ui/src/app/app.component.html
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.html
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.ts
Labels: P1 - Blocks Release

#1241 validate description length
  backend/src/s9pk/manifest.rs
  backend/src/s9pk/reader.rs
Labels: Enhancement, embassyd, P2 - Desirable

#1236 Update README.md
  build/README.md
Labels: Docs, Builds

#1245 mute crash notifications when service is just started
  backend/src/context/rpc.rs
  backend/src/manager/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1252 handle case where dependency-info is missing entry
  frontend/projects/ui/src/app/pages/apps-routes/app-show/pipes/to-dependencies.pipe.ts
  frontend/projects/ui/src/app/services/api/api.fixures.ts
Labels: Bug, P1 - Blocks Release

#1254 Update initialization.sh
  build/initialization.sh
Labels: Bug, P0 - Blocks Dev, Builds

#1257 noserverino
  backend/src/disk/mount/filesystem/cifs.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1260 Bugfix/fix syntax change user
  build/initialization.sh
Labels: Bug, P0 - Blocks Dev, Builds

#1262 fix NO_KEY initialization
  build/initialization.sh
Labels: Bug, P1 - Blocks Release, Builds

#1263 only show attach prompt if product key present
  frontend/projects/setup-wizard/src/app/pages/recover/recover.page.ts
Labels: P1 - Blocks Release

#1264 start with clean tor state
  build/initialization.sh
Labels: Bug, Builds

#1268 add success-message instead of description on health checks
  backend/src/status/health_check.rs
Labels: Enhancement, embassyd

#1276 add details
  frontend/projects/diagnostic-ui/src/app/pages/home/home.page.html
  frontend/projects/diagnostic-ui/src/app/pages/home/home.page.ts
Labels: UI, P1 - Blocks Release

#1249 Fix links in UI to point to new website
  CONTRIBUTING.md
  README.md
  build/00-embassy
  frontend/projects/setup-wizard/src/app/pages/recover/recover.page.html
  frontend/projects/setup-wizard/src/app/pages/success/success.page.html
  frontend/projects/ui/src/app/app.component.ts
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.html
  frontend/projects/ui/src/app/pages/server-routes/lan/lan.page.html
  frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
  frontend/projects/ui/src/app/pages/server-routes/ssh-keys/ssh-keys.page.ts
  frontend/projects/ui/src/app/pages/server-routes/wifi/wifi.page.html
  frontend/projects/ui/src/app/services/error-toast.service.ts
Labels: Docs, Enhancement, P1 - Blocks Release

#1278 adds warnings for extra manifest keys
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/bin/embassy-sdk.rs
  backend/src/s9pk/mod.rs
  backend/src/util/logger.rs
Labels: Enhancement, P2 - Desirable, embassy-sdk

#1281 send id to marketplace
  frontend/projects/ui/src/app/app.component.ts
  frontend/projects/ui/src/app/modals/snake/snake.page.ts
  frontend/projects/ui/src/app/pages/marketplace-routes/marketplace.service.ts
  frontend/projects/ui/src/app/pages/server-routes/marketplaces/marketplaces.page.ts
  frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
  frontend/projects/ui/src/app/services/api/api.types.ts
  frontend/projects/ui/src/app/services/eos.service.ts
Labels: P1 - Blocks Release

#1282 update Makefile to use js script
  Makefile
Labels: P1 - Blocks Release, Builds

#1286 update version in Cargo.toml
  backend/Cargo.toml
Labels: P1 - Blocks Release

#1295 base64 encode cert
  frontend/projects/setup-wizard/src/app/services/api/live-api.service.ts
Labels: P1 - Blocks Release

#1294 mute crash notifs during shutdown
  backend/src/manager/mod.rs
Labels: embassyd, P1 - Blocks Release

#1297 treat the old config as null when we install/recover for the first time
  backend/src/config/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release
