Repository Start9Labs/start-os, pull requests merged in 2022-07, with the labels that each got.

#1609 display bottom item in backup list and refactor for cleanliness
  frontend/projects/ui/src/app/components/backup-drives/backup-drives-header.component.html
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.html
  frontend/projects/ui/src/app/components/backup-drives/backup-drives.component.ts
  frontend/projects/ui/src/app/modals/app-recover-select/app-recover-select.page.html
  frontend/projects/ui/src/app/modals/app-recover-select/app-recover-select.page.ts
  frontend/projects/ui/src/app/modals/backup-select/backup-select.page.html
  frontend/projects/ui/src/app/modals/backup-select/backup-select.page.scss
  frontend/projects/ui/src/app/modals/backup-select/backup-select.page.ts
  frontend/projects/ui/src/app/pages/server-routes/restore/restore.component.html
  frontend/projects/ui/src/app/pages/server-routes/server-backup/server-backup.page.html
  frontend/projects/ui/src/app/services/api/embassy-api.service.ts
Labels: UI, P1 - Blocks Release

#1614 release lock on update progress
  backend/src/install/progress.rs
Labels: Bug, embassyd

#1617 remove beta flag actions from UI config build
  backend/Cargo.toml
  backend/build-prod.sh
  backend/src/lib.rs
  frontend/build-config.js
Labels: UI, Builds

#1622 Fix/misc UI
  frontend/package-lock.json
  frontend/package.json
  frontend/projects/shared/styles/shared.scss
  frontend/projects/ui/src/app/components/form-object/form-object.component.ts
  frontend/projects/ui/src/app/modals/action-marketplace/action-marketplace.component.html
  frontend/projects/ui/src/app/modals/action-marketplace/action-marketplace.component.module.ts
  frontend/projects/ui/src/app/modals/action-marketplace/action-marketplace.component.scss
  frontend/projects/ui/src/app/modals/action-marketplace/action-marketplace.component.ts
  frontend/projects/ui/src/app/modals/app-config/app-config.page.html
  frontend/projects/ui/src/app/modals/app-config/app-config.page.scss
  frontend/projects/ui/src/app/modals/generic-input/generic-input.component.module.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/app-show.module.ts
  frontend/projects/ui/src/app/pages/apps-routes/app-show/pipes/to-buttons.pipe.ts
Labels: Bug, UI

#1624 fix icons for sideloaded packages
  backend/src/install/mod.rs
Labels: Bug, embassyd

#1626 keep status if package has no config
  backend/src/install/mod.rs
Labels: Bug, embassyd

#1630 🐋 docker stats fix
  build/initialization.sh
  build/write-image.sh
Labels: Bug, Builds

#1616 Fix/receipts health
  backend/src/manager/health.rs
  backend/src/status/mod.rs
Labels: Bug, embassyd

#1636 return correct error on failed os download
  backend/src/update/mod.rs
Labels: Bug, embassyd

#1639 fix build
  Makefile
  libs/Cargo.lock
  system-images/compat/Cargo.lock
  system-images/compat/Cargo.toml
Labels: Bug, System Images, Builds

#1653 sdk: don't allow mounts in inject actions
  backend/src/procedure/docker.rs
Labels: Enhancement

#1665 add readme to system-images folder
  system-images/README.md
Labels: Docs

#1669 feat: Make the rename effect
  backend/src/procedure/js_scripts.rs
  backend/test/js_action_execute/package-data/scripts/test-package/0.3.0.3/embassy.js
  libs/js_engine/src/artifacts/loadModule.js
  libs/js_engine/src/lib.rs
Labels: embassyd, embassy-sdk

#1674 fix migration, add logging
  backend/embassy-init.service
  backend/src/init.rs
  backend/src/version/mod.rs
  backend/src/version/v0_3_1_1.rs
Labels: Bug, embassyd, P0 - Blocks Dev

#1670 trust local ca
  backend/src/net/ssl.rs
Labels: Bug, embassyd

#1675 refactor build process
  .github/workflows/backend-pr.yaml
  .github/workflows/frontend-pr.yaml
  .github/workflows/product.yaml
  .gitignore
  Makefile
  backend/Cargo.lock
  backend/Cargo.toml
  backend/build-dev.sh
  backend/build-portable-dev.sh
  backend/build-portable.sh
  backend/build-prod.sh
  build-cargo-dep.sh
  build/initialization.service
  build/initialization.sh
  build/nc-broadcast.service
  build/partitioning.sh
  build/user-data
  build/user-data-dev
  build/write-image.sh
  check-environment.sh
  check-git-hash.sh
  frontend/build-config.js
  frontend/config-sample.json
  frontend/package-lock.json
  frontend/package.json
  frontend/projects/ui/postprocess.ts
  frontend/registries.json
  system-images/compat/Cargo.lock
Labels: Refactor, Builds

#1671 add standby mode
  backend/src/bin/embassy-init.rs
  backend/src/init.rs
  backend/src/shutdown.rs
Labels: Enhancement, embassyd, P0 - Blocks Dev

#1679 allow server.update to update to current version
  backend/src/update/mod.rs
  libs/Cargo.lock
Labels: Enhancement, embassyd

#1680 allow falsey rpc response
  frontend/projects/diagnostic-ui/src/app/services/http.service.ts
  frontend/projects/setup-wizard/src/app/services/api/http.service.ts
  frontend/projects/ui/src/app/modals/app-config/app-config.page.ts
  frontend/projects/ui/src/app/services/http.service.ts
Labels: Bug, UI

#1685 issue notification when individual package restore fails
  backend/src/backup/restore.rs
Labels: Bug, embassyd

#1686 only validate mounts for inject if eos `>=0.3.1.1`
  backend/src/action.rs
  backend/src/backup/mod.rs
  backend/src/config/action.rs
  backend/src/context/rpc.rs
  backend/src/init.rs
  backend/src/migration.rs
  backend/src/procedure/docker.rs
  backend/src/procedure/mod.rs
  backend/src/s9pk/reader.rs
  backend/src/status/health_check.rs
Labels: Bug, embassyd, embassy-sdk

#1688 add marketplace_url to backup metadata for service
  backend/src/backup/backup_bulk.rs
  backend/src/backup/mod.rs
Labels: Enhancement, embassyd

#1689 marketplace published at for service
  frontend/projects/marketplace/src/pages/show/package/package.component.html
  frontend/projects/marketplace/src/pages/show/package/package.component.scss
  frontend/projects/marketplace/src/types/marketplace-pkg.ts
  frontend/projects/ui/src/app/services/api/api.fixures.ts
Labels: Enhancement, UI

#1690 sync data to fs before shutdown
  backend/src/bin/embassy-init.rs
  backend/src/disk/main.rs
  backend/src/shutdown.rs
Labels: Bug, embassyd

#1692 honor shutdown from diagnostic ui
  backend/src/bin/embassyd.rs
Labels: Bug, embassyd

#1693 ask for sudo password immediately during make
  Makefile
Labels: Enhancement, Builds

#1694 sync blockdev after update
  backend/src/update/mod.rs
Labels: Bug, embassyd

#1700 NO_KEY for CI images
  .github/workflows/product.yaml
Labels: Builds

#1702 fix typo
  frontend/projects/ui/src/app/pages/server-routes/server-show/server-show.page.ts
Labels: Bug, UI
