Repository Start9Labs/start-os, pull requests merged in 2022-05, with the labels that each got.

#1420 attempt to heal when health check passes
  backend/src/manager/health.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1419 Update index.html
  index.html
Labels: UI, P3 - Eventual

#1321 Switching SSH keys to start9 user
  backend/copy.sh
  backend/src/init.rs
  backend/src/ssh.rs
  build/write-image.sh
Labels: Enhancement, embassyd, Community

#1414 Fix/id params
  Makefile
  frontend/projects/ui/src/app/services/api/api.fixures.ts
  frontend/projects/ui/src/app/services/api/api.types.ts
  frontend/projects/ui/src/app/services/marketplace.service.ts
Labels: Bug, UI, P2 - Desirable

#1438 make nicer update sound
  backend/src/update/mod.rs
Labels: embassyd, P1 - Blocks Release

#1385 Update README.md to include yq
  build/README.md
Labels: Docs, Needs Triage

#1453 refactor packing to async
  backend/Cargo.toml
  backend/src/action.rs
  backend/src/s9pk/builder.rs
  backend/src/s9pk/header.rs
  backend/src/s9pk/mod.rs
  backend/src/util/io.rs
  backend/src/util/mod.rs
  backend/src/util/serde.rs
Labels: Refactor

#1421 Add nginx config for proxy redirect
  backend/src/net/nginx.conf.template
  backend/src/net/nginx.rs
Labels: Bug, embassyd, Community
