Repository Start9Labs/start-os, pull requests merged in 2022-08, with the labels that each got.

#1709 write image to sparse-aware archive format
  .github/workflows/product.yaml
  .gitignore
  Makefile
Labels: Builds

#1722 fix build for patch-db client for consistency
  Makefile
Labels: UI, Builds

#1741 Bugfix/dns
  backend/src/net/wifi.rs
  build/initialization.sh
Labels: Bug, embassyd, Builds

#1682 add x86 build and run unittests to backend pipeline
  .github/workflows/README.md
  .github/workflows/backend-pr.yaml
  .github/workflows/backend.yaml
  .github/workflows/frontend.yaml
  .github/workflows/product.yaml
Labels: embassyd, Builds

#1746 [feat]: resumable downloads
  backend/Cargo.toml
  backend/src/util/http_reader.rs
Labels: Enhancement, embassyd
