Repository Start9Labs/start-os, pull requests merged in 2022-01, with the labels that each got.

#1022 add richer error codes to disk import
  appmgr/src/disk/main.rs
Labels: embassyd, P1 - Blocks Release

#1024 added clarification on the embassy.local address being turned off aft…
  build/README.md
  setup-wizard/src/app/pages/success/success.page.html
Labels: Enhancement, UI, P4 - Community

#1014 set owner
  appmgr/src/setup.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1037 nav guard bugfix
  setup-wizard/src/app/app-routing.module.ts
  setup-wizard/src/app/guards/nav-guard.ts
  setup-wizard/src/app/services/api/mock-api.service.ts
Labels: Bug, UI, Needs Triage

#1030 adds support for no product key builds as well as chosen product key …
  Makefile
  build/write-image.sh
Labels: Enhancement, P1 - Blocks Release, Builds

#1015 feat: Wifi swapped to NMCli
  Makefile
  appmgr/src/context/rpc.rs
  appmgr/src/db/model.rs
  appmgr/src/init.rs
  appmgr/src/net/wifi.rs
  appmgr/src/nginx/main-ui.conf.template
  build/initialization.sh
  ui/package-lock.json
  ui/src/app/pages/server-routes/wifi/wifi.page.html
  ui/src/app/pages/server-routes/wifi/wifi.page.ts
  ui/src/app/services/api/api.fixures.ts
  ui/src/app/services/api/api.types.ts
Labels: Enhancement, embassyd, P1 - Blocks Release

#1049 removed broken packages entry in patchdb
  appmgr/src/db/model.rs
  appmgr/src/install/mod.rs
Labels: Enhancement, embassyd, P2 - Desirable

#1052 add .embassy domains to system-generated ssl certs
  appmgr/src/net/mod.rs
  appmgr/src/net/nginx.rs
  appmgr/src/net/ssl.rs
Labels: Enhancement, embassyd, P2 - Desirable

#1067 fixes issue where hostnames would change on package reinstall/update
  appmgr/src/action/docker.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1064 health name off manifest
  ui/src/app/pages/apps-routes/app-show/components/app-show-health-checks/app-show-health-checks.component.html
Labels: Enhancement, UI, P2 - Desirable

#1053 reconfigures dependents with live pointers when package is installed …
  appmgr/src/backup/mod.rs
  appmgr/src/config/spec.rs
  appmgr/src/dependencies.rs
  appmgr/src/install/cleanup.rs
  appmgr/src/install/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1084 refresh button in embassy drive page in wizard
  setup-wizard/src/app/pages/embassy/embassy.page.html
  setup-wizard/src/app/pages/embassy/embassy.page.ts
  setup-wizard/src/app/services/api/mock-api.service.ts
Labels: P1 - Blocks Release

#1085 highlight text
  ui/src/global.scss
Labels: Bug, P2 - Desirable

#1099 fix bug where migrations would only run if the service was previously…
  appmgr/src/install/mod.rs
Labels: Bug, embassyd

#1100 clear dmsetup before import
  appmgr/src/disk/main.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1095 unplug notification
  setup-wizard/src/app/pages/success/success.page.html
Labels: P1 - Blocks Release

#1103 use cloud-init correctly
  build/initialization.sh
  build/user-data
  build/user-data-dev
  build/write-image.sh
Labels: Bug, Builds

#1105 Integration/02x migration fixes
  appmgr/src/bin/embassy-init.rs
  appmgr/src/context/rpc.rs
  appmgr/src/context/setup.rs
  appmgr/src/error.rs
  appmgr/src/hostname.rs
  appmgr/src/init.rs
  appmgr/src/setup.rs
  setup-wizard/src/app/pages/recover/recover.page.ts
Labels: Bug, embassyd, P1 - Blocks Release

#1102 return null for tor-key pointer if doesn't exist
  appmgr/src/config/spec.rs
Labels: Bug, embassyd

#1106 fixes shutdown issues
  appmgr/src/manager/mod.rs
  appmgr/src/manager/sync.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1101 hard restart feature
  ui/src/app/pages/server-routes/server-show/server-show.page.ts
  ui/src/app/services/api/api.types.ts
  ui/src/app/services/api/embassy-api.service.ts
  ui/src/app/services/api/embassy-live-api.service.ts
  ui/src/app/services/api/embassy-mock-api.service.ts
Labels: Enhancement, UI, P1 - Blocks Release

#1118 build docker state on first startup
  build/write-image.sh
Labels: Bug, Builds

#1114 Clean up README
  BuildGuide.md
  CONTRIBUTING.md
  README.md
  assets/EmbassyOS.png
  assets/eos-bitcoind-health-check.png
  assets/eos-logs.png
  assets/eos-preferences.png
  assets/eos-services.png
  backend/README.md
  backend/install-sdk.sh
  build/NOTES.md
  build/README.md
  build/README.old.md
  diagnostic-ui/README.md
  lifeline/.gitignore
  lifeline/Cargo.lock
  lifeline/Cargo.toml
  lifeline/lifeline.service
  lifeline/rustfmt.toml
  lifeline/src/main.rs
  lifeline/src/sound.rs
  setup-wizard/README.md
  ui/README.md
  ui/package.json
Labels: Docs, Needs Triage

#1126 fix arrangement and sizing of screenshots
  README.md
Labels: Enhancement, Needs Triage

#1116 Custom MOTD for EmbassyOS
  build/00-embassy
  build/write-image.sh
Labels: Enhancement, P4 - Community

#1131 fixes lock ordering issue in recovery
  backend/src/setup.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1133 fix version
  ui/src/app/pages/apps-routes/app-list/app-list-rec/app-list-rec.component.ts
Labels: Bug, UI, P1 - Blocks Release

#1142 registry.start9.com -> marketplace.start9.com
  backend/src/db/model.rs
Labels: embassyd, P1 - Blocks Release

#1143 forcefully remove the container, blowing past 409s
  backend/src/action/docker.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1125 Update CONTRIBUTING.md
  CONTRIBUTING.md
  backend/README.md
Labels: Docs, P1 - Blocks Release

#1145 adds some investigative logging and improves error handling for mdns
  backend/src/net/mdns.rs
Labels: Enhancement, embassyd, P0 - Blocks Dev

#1156 set journald conf file
  build/journald.conf
  build/write-image.sh
Labels: Enhancement, embassyd, P1 - Blocks Release

#1157 update marked to latest version
  frontend/package-lock.json
  frontend/package.json
  frontend/projects/ui/src/app/pipes/markdown.pipe.ts
Labels: UI, P1 - Blocks Release, SECURITY
