Repository Start9Labs/start-os, pull requests merged in 2022-04, with the labels that each got.

#1375 allow for multiple disk repairs
  backend/src/bin/embassy-init.rs
  backend/src/disk/fsck.rs
  backend/src/disk/main.rs
Labels: Bug, embassyd

#1377 fix migrations not running in the `to` block
  backend/src/install/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1381 dont hang on update and downgrade
  frontend/projects/ui/src/app/components/install-wizard/prebaked-wizards.ts
  frontend/projects/ui/src/app/services/api/api.fixures.ts
Labels: Bug, UI, P1 - Blocks Release

#1388 commit compat after update
  backend/src/version/mod.rs
Labels: Bug, embassyd, P1 - Blocks Release

#1402 prevent the kernel from OOMKilling embassyd
  backend/embassyd.service
  build/docker-engine.slice
  build/initialization.sh
Labels: Enhancement, P1 - Blocks Release, Builds
